services:
  postgres:
    image: postgres:18
    restart: no
    ports:
      - "5433:5433"
    volumes:
      - maia_db:/var/lib/postgresql/maia/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: huh_db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ops@maiaframework.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/maia/pgadmin
volumes:
  maia_db:
  pgadmin-data:
